# Generated by Django 5.0.7 on 2024-07-30 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepayment',
            name='document',
            field=models.FileField(default=0, upload_to='employee_payment_slip/'),
            preserve_default=False,
        ),
    ]
