# Generated by Django 5.0.6 on 2024-07-25 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='title',
            new_name='name',
        ),
    ]
