# Generated by Django 5.0.7 on 2024-07-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginsystem',
            name='emp_id',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
