# Generated by Django 5.0.7 on 2024-08-26 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_subscription_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginsystem',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='core.company'),
            preserve_default=False,
        ),
    ]
