# Generated by Django 5.1.4 on 2024-12-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_loginsystem_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginsystem',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
