# Generated by Django 5.0.6 on 2024-07-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_loginsystem_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginsystem',
            name='profile_pictures',
            field=models.ImageField(upload_to='profile_pictures/'),
        ),
    ]
