# Generated by Django 5.1.4 on 2024-12-30 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_loginsystem_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginsystem',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='core.company'),
        ),
    ]
