# Generated by Django 5.0.6 on 2024-07-26 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_loginsystem_profile_pictures'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='loginsystem',
            managers=[
            ],
        ),
    ]
