# Generated by Django 5.0.6 on 2024-07-26 07:30

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_loginsystem_managers_loginsystem_id_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='loginsystem',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='loginsystem',
            name='id',
        ),
        migrations.AlterField(
            model_name='loginsystem',
            name='emp_id',
            field=models.CharField(default=core.models.generate_emp_id, max_length=11, primary_key=True, serialize=False),
        ),
    ]
