# Generated by Django 5.0.6 on 2024-07-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_loginsystem_managers_remove_loginsystem_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginsystem',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
