# Generated by Django 5.0.6 on 2024-07-26 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_loginsystem_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginsystem',
            name='is_superuser',
            field=models.BooleanField(default=True),
        ),
    ]
