# Generated by Django 5.0.6 on 2024-07-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_loginsystem_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginsystem',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
    ]
