# Generated by Django 5.0.6 on 2024-07-26 11:03

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_loginsystem_is_superuser'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='loginsystem',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='loginsystem',
            name='id',
            field=models.PositiveIntegerField(db_index=True, default=1, unique=True),
            preserve_default=False,
        ),
    ]
