# Generated by Django 5.0.6 on 2024-07-26 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_loginsystem_managers_loginsystem_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginsystem',
            name='id',
        ),
    ]
