# Generated by Django 5.0.6 on 2024-07-26 11:13

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_loginsystem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginsystem',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loginsystem',
            name='emp_id',
            field=models.CharField(default=core.models.generate_emp_id, max_length=11, unique=True),
        ),
    ]
