# Generated by Django 5.0.6 on 2024-07-26 06:02

import Token_System.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('token_number', models.CharField(default=Token_System.models.generate_token_id, max_length=15, primary_key=True, serialize=False)),
                ('is_complated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
