# Generated by Django 5.0.6 on 2024-07-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Token_System', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='is_active',
        ),
        migrations.AddField(
            model_name='token',
            name='is_complated',
            field=models.BooleanField(default=False),
        ),
    ]
