# Generated by Django 5.0.6 on 2024-07-25 11:07

import Token_System.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Token_System', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='id',
        ),
        migrations.AlterField(
            model_name='token',
            name='token_number',
            field=models.CharField(default=Token_System.models.generate_token_id, max_length=15, primary_key=True, serialize=False),
        ),
    ]
