# Generated by Django 5.0.6 on 2024-07-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Token_System', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenorderitem',
            name='extra_tip',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
