# Generated by Django 5.0.7 on 2024-07-30 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_supplier_email_alter_supplier_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=255),
        ),
    ]
