# Generated by Django 5.0.7 on 2024-08-25 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='availability',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
