# Generated by Django 5.0.6 on 2024-07-25 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0002_order_is_active'),
        ('crm', '0003_remove_customer_id_alter_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='crm.customer'),
        ),
    ]
