# Generated by Django 5.0.6 on 2024-07-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='table_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='extra_tip',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
