# Generated by Django 5.0.6 on 2024-07-25 10:49

import Orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0002_order_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=Orders.models.generate_order_id, max_length=13, primary_key=True, serialize=False),
        ),
    ]
